from awm.models.base_model_ import Model
from awm.models.allocation import Allocation
from awm import util


class AllocationInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, allocation: Allocation = None, _id: str = None, _self: str = None):
        """AllocationInfo - a model defined in Swagger

        :param allocation: The allocation of this Deployment.
        :type allocation: Allocation
        :param id: The id of this Deployment.
        :type id: str
        :param self: The self of this Deployment.
        :type self: str
        """
        self.swagger_types = {
            'allocation': Allocation,
            '_id': str,
            '_self': str
        }

        self.attribute_map = {
            'allocation': 'allocation',
            '_id': 'id',
            '_self': 'self'
        }
        self._allocation = allocation
        self.__id = _id
        self.__self = _self

    @classmethod
    def from_dict(cls, dikt) -> 'AllocationInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllocationInfo of this AllocationInfo.  # noqa: E501
        :rtype: AllocationInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def allocation(self) -> Allocation:
        """Gets the allocation of this Deployment.

        Where to deploy it  # noqa: E501

        :return: The allocation of this Deployment.
        :rtype: Allocation
        """
        return self._allocation

    @allocation.setter
    def allocation(self, allocation: Allocation):
        """Sets the allocation of this Deployment.

        Where to deploy it  # noqa: E501

        :param allocation: The allocation of this Deployment.
        :type allocation: Allocation
        """
        if allocation is None:
            raise ValueError("Invalid value for `allocation`, must not be `None`")  # noqa: E501

        self._allocation = allocation

    @property
    def _id(self) -> str:
        """Gets the id of this Deployment.

        The deployment id  # noqa: E501

        :return: The id of this Deployment.
        :rtype: str
        """
        return self.__id

    @_id.setter
    def _id(self, _id: str):
        """Sets the id of this Deployment.

        The deployment id  # noqa: E501

        :param id: The id of this Deployment.
        :type id: str
        """
        if _id is None:
            raise ValueError("Invalid value for `_id`, must not be `None`")  # noqa: E501

        self.__id = _id

    @property
    def _self(self) -> str:
        """Gets the self of this Deployment.

        The deployment URL  # noqa: E501

        :return: The self of this Deployment.
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self: str):
        """Sets the self of this Deployment.

        The deployment URL  # noqa: E501

        :param self: The self of this Deployment.
        :type self: str
        """
        if _self is None:
            raise ValueError("Invalid value for `_self`, must not be `None`")  # noqa: E501

        self.__self = _self
