from awm.models.allocation import Allocation
from awm import util


class CredentialsOpenStack(Allocation):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, kind: str = None, user_name: str = None, domain: str = None,
                 domain_id: str = None, tenant: str = None, tenant_id: str = None,
                 region: str = None, host: str = None, auth_version: str = None,
                 api_version: str = None):  # noqa: E501
        """CredentialsOpenStack - a model defined in Swagger

        :param kind: The kind of this CredentialsOpenStack.  # noqa: E501
        :type kind: str
        :param user_name: The user_name of this CredentialsOpenStack.  # noqa: E501
        :type user_name: str
        :param domain: The domain of this CredentialsOpenStack.  # noqa: E501
        :type domain: str
        :param domain_id: The domain_id of this CredentialsOpenStack.  # noqa: E501
        :type domain_id: str
        :param tenant: The tenant of this CredentialsOpenStack.  # noqa: E501
        :type tenant: str
        :param tenant_id: The tenant_id of this CredentialsOpenStack.  # noqa: E501
        :type tenant_id: str
        :param region: The region of this CredentialsOpenStack.  # noqa: E501
        :type region: str
        :param host: The host of this CredentialsOpenStack.  # noqa: E501
        :type host: str
        :param auth_version: The auth_version of this CredentialsOpenStack.  # noqa: E501
        :type auth_version: str
        :param api_version: The api_version of this CredentialsOpenStack.  # noqa: E501
        :type api_version: str
        """
        self.swagger_types = {
            'kind': str,
            'user_name': str,
            'domain': str,
            'domain_id': str,
            'tenant': str,
            'tenant_id': str,
            'region': str,
            'host': str,
            'auth_version': str,
            'api_version': str
        }

        self.attribute_map = {
            'kind': 'kind',
            'user_name': 'userName',
            'domain': 'domain',
            'domain_id': 'domainId',
            'tenant': 'tenant',
            'tenant_id': 'tenantId',
            'region': 'region',
            'host': 'host',
            'auth_version': 'authVersion',
            'api_version': 'apiVersion'
        }
        self._kind = kind
        self._user_name = user_name
        self._domain = domain
        self._domain_id = domain_id
        self._tenant = tenant
        self._tenant_id = tenant_id
        self._region = region
        self._host = host
        self._auth_version = auth_version
        self._api_version = api_version

    @classmethod
    def from_dict(cls, dikt) -> 'CredentialsOpenStack':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CredentialsOpenStack of this CredentialsOpenStack.  # noqa: E501
        :rtype: CredentialsOpenStack
        """
        return util.deserialize_model(dikt, cls)

    @property
    def kind(self) -> str:
        """Gets the kind of this CredentialsOpenStack.


        :return: The kind of this CredentialsOpenStack.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind: str):
        """Sets the kind of this CredentialsOpenStack.


        :param kind: The kind of this CredentialsOpenStack.
        :type kind: str
        """
        if kind is None:
            raise ValueError("Invalid value for `kind`, must not be `None`")  # noqa: E501

        self._kind = kind

    @property
    def user_name(self) -> str:
        """Gets the user_name of this CredentialsOpenStack.


        :return: The user_name of this CredentialsOpenStack.
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name: str):
        """Sets the user_name of this CredentialsOpenStack.


        :param user_name: The user_name of this CredentialsOpenStack.
        :type user_name: str
        """

        self._user_name = user_name

    @property
    def domain(self) -> str:
        """Gets the domain of this CredentialsOpenStack.


        :return: The domain of this CredentialsOpenStack.
        :rtype: str
        """
        return self._domain

    @domain.setter
    def domain(self, domain: str):
        """Sets the domain of this CredentialsOpenStack.


        :param domain: The domain of this CredentialsOpenStack.
        :type domain: str
        """

        self._domain = domain

    @property
    def domain_id(self) -> str:
        """Gets the domain_id of this CredentialsOpenStack.


        :return: The domain_id of this CredentialsOpenStack.
        :rtype: str
        """
        return self._domain_id

    @domain_id.setter
    def domain_id(self, domain_id: str):
        """Sets the domain_id of this CredentialsOpenStack.


        :param domain_id: The domain_id of this CredentialsOpenStack.
        :type domain_id: str
        """

        self._domain_id = domain_id

    @property
    def tenant(self) -> str:
        """Gets the tenant of this CredentialsOpenStack.


        :return: The tenant of this CredentialsOpenStack.
        :rtype: str
        """
        return self._tenant

    @tenant.setter
    def tenant(self, tenant: str):
        """Sets the tenant of this CredentialsOpenStack.


        :param tenant: The tenant of this CredentialsOpenStack.
        :type tenant: str
        """

        self._tenant = tenant

    @property
    def tenant_id(self) -> str:
        """Gets the tenant_id of this CredentialsOpenStack.


        :return: The tenant_id of this CredentialsOpenStack.
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id: str):
        """Sets the tenant_id of this CredentialsOpenStack.


        :param tenant_id: The tenant_id of this CredentialsOpenStack.
        :type tenant_id: str
        """

        self._tenant_id = tenant_id

    @property
    def region(self) -> str:
        """Gets the region of this CredentialsOpenStack.


        :return: The region of this CredentialsOpenStack.
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region: str):
        """Sets the region of this CredentialsOpenStack.


        :param region: The region of this CredentialsOpenStack.
        :type region: str
        """

        self._region = region

    @property
    def host(self) -> str:
        """Gets the host of this CredentialsOpenStack.


        :return: The host of this CredentialsOpenStack.
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host: str):
        """Sets the host of this CredentialsOpenStack.


        :param host: The host of this CredentialsOpenStack.
        :type host: str
        """
        if host is None:
            raise ValueError("Invalid value for `host`, must not be `None`")  # noqa: E501

        self._host = host

    @property
    def auth_version(self) -> str:
        """Gets the auth_version of this CredentialsOpenStack.


        :return: The auth_version of this CredentialsOpenStack.
        :rtype: str
        """
        return self._auth_version

    @auth_version.setter
    def auth_version(self, auth_version: str):
        """Sets the auth_version of this CredentialsOpenStack.


        :param auth_version: The auth_version of this CredentialsOpenStack.
        :type auth_version: str
        """
        if auth_version is None:
            raise ValueError("Invalid value for `auth_version`, must not be `None`")  # noqa: E501

        self._auth_version = auth_version

    @property
    def api_version(self) -> str:
        """Gets the api_version of this CredentialsOpenStack.


        :return: The api_version of this CredentialsOpenStack.
        :rtype: str
        """
        return self._api_version

    @api_version.setter
    def api_version(self, api_version: str):
        """Sets the api_version of this CredentialsOpenStack.


        :param api_version: The api_version of this CredentialsOpenStack.
        :type api_version: str
        """

        self._api_version = api_version
