from awm.models.base_model_ import Model
from awm import util


class Credentials(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """Credentials - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Credentials':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Credentials of this Credentials.  # noqa: E501
        :rtype: Credentials
        """
        return util.deserialize_model(dikt, cls)
