from awm.models.allocation import Allocation
from awm import util


class CredentialsKubernetes(Allocation):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, kind: str = None, host: str = None):  # noqa: E501
        """CredentialsKubernetes - a model defined in Swagger

        :param kind: The kind of this CredentialsKubernetes.  # noqa: E501
        :type kind: str
        :param host: The host of this CredentialsKubernetes.  # noqa: E501
        :type host: str
        """
        self.swagger_types = {
            'kind': str,
            'host': str
        }

        self.attribute_map = {
            'kind': 'kind',
            'host': 'host'
        }
        self._kind = kind
        self._host = host

    @classmethod
    def from_dict(cls, dikt) -> 'CredentialsKubernetes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CredentialsKubernetes of this CredentialsKubernetes.  # noqa: E501
        :rtype: CredentialsKubernetes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def kind(self) -> str:
        """Gets the kind of this CredentialsKubernetes.


        :return: The kind of this CredentialsKubernetes.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind: str):
        """Sets the kind of this CredentialsKubernetes.


        :param kind: The kind of this CredentialsKubernetes.
        :type kind: str
        """
        if kind is None:
            raise ValueError("Invalid value for `kind`, must not be `None`")  # noqa: E501

        self._kind = kind

    @property
    def host(self) -> str:
        """Gets the host of this CredentialsKubernetes.


        :return: The host of this CredentialsKubernetes.
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host: str):
        """Sets the host of this CredentialsKubernetes.


        :param host: The host of this CredentialsKubernetes.
        :type host: str
        """
        if host is None:
            raise ValueError("Invalid value for `host`, must not be `None`")  # noqa: E501

        self._host = host
