from awm.models.base_model_ import Model
from awm.models.allocation import Allocation  # noqa: F401,E501
from awm.models.tool import Tool  # noqa: F401,E501
from awm import util


class Deployment(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tool: Tool = None, allocation: Allocation = None):  # noqa: E501
        """Deployment - a model defined in Swagger

        :param tool: The tool of this Deployment.  # noqa: E501
        :type tool: Tool
        :param allocation: The allocation of this Deployment.  # noqa: E501
        :type allocation: Allocation
        """
        self.swagger_types = {
            'tool': Tool,
            'allocation': Allocation
        }

        self.attribute_map = {
            'tool': 'tool',
            'allocation': 'allocation'
        }
        self._tool = tool
        self._allocation = allocation

    @classmethod
    def from_dict(cls, dikt) -> 'Deployment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Deployment of this Deployment.  # noqa: E501
        :rtype: Deployment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tool(self) -> Tool:
        """Gets the tool of this Deployment.

        What to deploy  # noqa: E501

        :return: The tool of this Deployment.
        :rtype: Tool
        """
        return self._tool

    @tool.setter
    def tool(self, tool: Tool):
        """Sets the tool of this Deployment.

        What to deploy  # noqa: E501

        :param tool: The tool of this Deployment.
        :type tool: Tool
        """
        if tool is None:
            raise ValueError("Invalid value for `tool`, must not be `None`")  # noqa: E501

        self._tool = tool

    @property
    def allocation(self) -> Allocation:
        """Gets the allocation of this Deployment.

        Where to deploy it  # noqa: E501

        :return: The allocation of this Deployment.
        :rtype: Allocation
        """
        return self._allocation

    @allocation.setter
    def allocation(self, allocation: Allocation):
        """Sets the allocation of this Deployment.

        Where to deploy it  # noqa: E501

        :param allocation: The allocation of this Deployment.
        :type allocation: Allocation
        """
        if allocation is None:
            raise ValueError("Invalid value for `allocation`, must not be `None`")  # noqa: E501

        self._allocation = allocation
