from awm.models.base_model_ import Model
from awm.models.allocation import Allocation
from awm.models.tool import Tool
from awm import util


class DeploymentInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tool: Tool = None, allocation: Allocation = None,
                 _id: str = None, status: str = None, _self: str = None):
        """Deployment - a model defined in Swagger

        :param tool: The tool of this Deployment.
        :type tool: Tool
        :param allocation: The allocation of this Deployment.
        :type allocation: Allocation
        :param id: The id of this Deployment.
        :type id: str
        :param status: The status of this Deployment.
        :type status: str
        :param self: The self of this Deployment.
        :type self: str
        """
        self.swagger_types = {
            'tool': Tool,
            'allocation': Allocation,
            '_id': str,
            'status': str,
            '_self': str
        }

        self.attribute_map = {
            'tool': 'tool',
            'allocation': 'allocation',
            '_id': 'id',
            'status': 'status',
            '_self': 'self'
        }
        self._tool = tool
        self._allocation = allocation
        self.__id = _id
        self._status = status
        self.__self = _self

    @classmethod
    def from_dict(cls, dikt) -> 'DeploymentInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Deployment of this Deployment.
        :rtype: Deployment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tool(self) -> Tool:
        """Gets the tool of this Deployment.

        What to deploy

        :return: The tool of this Deployment.
        :rtype: Tool
        """
        return self._tool

    @tool.setter
    def tool(self, tool: Tool):
        """Sets the tool of this Deployment.

        What to deploy

        :param tool: The tool of this Deployment.
        :type tool: Tool
        """
        if tool is None:
            raise ValueError("Invalid value for `tool`, must not be `None`")

        self._tool = tool

    @property
    def allocation(self) -> Allocation:
        """Gets the allocation of this Deployment.

        Where to deploy it

        :return: The allocation of this Deployment.
        :rtype: Allocation
        """
        return self._allocation

    @allocation.setter
    def allocation(self, allocation: Allocation):
        """Sets the allocation of this Deployment.

        Where to deploy it

        :param allocation: The allocation of this Deployment.
        :type allocation: Allocation
        """
        if allocation is None:
            raise ValueError("Invalid value for `allocation`, must not be `None`")

        self._allocation = allocation

    @property
    def _id(self) -> str:
        """Gets the id of this Deployment.

        The deployment id

        :return: The id of this Deployment.
        :rtype: str
        """
        return self.__id

    @_id.setter
    def _id(self, _id: str):
        """Sets the id of this Deployment.

        The deployment id

        :param id: The id of this Deployment.
        :type id: str
        """
        if _id is None:
            raise ValueError("Invalid value for `_id`, must not be `None`")

        self.__id = _id

    @property
    def status(self) -> str:
        """Gets the status of this Deployment.

        The deployment status

        :return: The status of this Deployment.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Deployment.

        The deployment status

        :param status: The status of this Deployment.
        :type status: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")

        self._status = status

    @property
    def _self(self) -> str:
        """Gets the self of this Deployment.

        The deployment URL

        :return: The self of this Deployment.
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self: str):
        """Sets the self of this Deployment.

        The deployment URL

        :param self: The self of this Deployment.
        :type self: str
        """
        if _self is None:
            raise ValueError("Invalid value for `_self`, must not be `None`")

        self.__self = _self
