from awm.models.base_model_ import Model
from awm import util


class EoscNodeEnvironmentOffer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, offer_id: str = None, offer_name: str = None, offer_type: str = None,
                 cpus: int = None, gpus: int = None, memory: int = None, fast_storage: int = None,
                 bulk_storage: int = None, s3_storage: int = None, registry_storage: int = None,
                 credits_per_day: int = None):  # noqa: E501
        """EoscNodeEnvironmentOffer - a model defined in Swagger

        :param offer_id: The offer_id of this EoscNodeEnvironmentOffer.  # noqa: E501
        :type offer_id: str
        :param offer_name: The offer_name of this EoscNodeEnvironmentOffer.  # noqa: E501
        :type offer_name: str
        :param offer_type: The offer_type of this EoscNodeEnvironmentOffer.  # noqa: E501
        :type offer_type: str
        :param cpus: The cpus of this EoscNodeEnvironmentOffer.  # noqa: E501
        :type cpus: int
        :param gpus: The gpus of this EoscNodeEnvironmentOffer.  # noqa: E501
        :type gpus: int
        :param memory: The memory of this EoscNodeEnvironmentOffer.  # noqa: E501
        :type memory: int
        :param fast_storage: The fast_storage of this EoscNodeEnvironmentOffer.  # noqa: E501
        :type fast_storage: int
        :param bulk_storage: The bulk_storage of this EoscNodeEnvironmentOffer.  # noqa: E501
        :type bulk_storage: int
        :param s3_storage: The s3_storage of this EoscNodeEnvironmentOffer.  # noqa: E501
        :type s3_storage: int
        :param registry_storage: The registry_storage of this EoscNodeEnvironmentOffer.  # noqa: E501
        :type registry_storage: int
        :param credits_per_day: The credits_per_day of this EoscNodeEnvironmentOffer.  # noqa: E501
        :type credits_per_day: int
        """
        self.swagger_types = {
            'offer_id': str,
            'offer_name': str,
            'offer_type': str,
            'cpus': int,
            'gpus': int,
            'memory': int,
            'fast_storage': int,
            'bulk_storage': int,
            's3_storage': int,
            'registry_storage': int,
            'credits_per_day': int
        }

        self.attribute_map = {
            'offer_id': 'offerId',
            'offer_name': 'offerName',
            'offer_type': 'offerType',
            'cpus': 'cpus',
            'gpus': 'gpus',
            'memory': 'memory',
            'fast_storage': 'fastStorage',
            'bulk_storage': 'bulkStorage',
            's3_storage': 's3Storage',
            'registry_storage': 'registryStorage',
            'credits_per_day': 'creditsPerDay'
        }
        self._offer_id = offer_id
        self._offer_name = offer_name
        self._offer_type = offer_type
        self._cpus = cpus
        self._gpus = gpus
        self._memory = memory
        self._fast_storage = fast_storage
        self._bulk_storage = bulk_storage
        self._s3_storage = s3_storage
        self._registry_storage = registry_storage
        self._credits_per_day = credits_per_day

    @classmethod
    def from_dict(cls, dikt) -> 'EoscNodeEnvironmentOffer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EoscNodeEnvironment_offer of this EoscNodeEnvironmentOffer.  # noqa: E501
        :rtype: EoscNodeEnvironmentOffer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def offer_id(self) -> str:
        """Gets the offer_id of this EoscNodeEnvironmentOffer.


        :return: The offer_id of this EoscNodeEnvironmentOffer.
        :rtype: str
        """
        return self._offer_id

    @offer_id.setter
    def offer_id(self, offer_id: str):
        """Sets the offer_id of this EoscNodeEnvironmentOffer.


        :param offer_id: The offer_id of this EoscNodeEnvironmentOffer.
        :type offer_id: str
        """
        if offer_id is None:
            raise ValueError("Invalid value for `offer_id`, must not be `None`")  # noqa: E501

        self._offer_id = offer_id

    @property
    def offer_name(self) -> str:
        """Gets the offer_name of this EoscNodeEnvironmentOffer.


        :return: The offer_name of this EoscNodeEnvironmentOffer.
        :rtype: str
        """
        return self._offer_name

    @offer_name.setter
    def offer_name(self, offer_name: str):
        """Sets the offer_name of this EoscNodeEnvironmentOffer.


        :param offer_name: The offer_name of this EoscNodeEnvironmentOffer.
        :type offer_name: str
        """

        self._offer_name = offer_name

    @property
    def offer_type(self) -> str:
        """Gets the offer_type of this EoscNodeEnvironmentOffer.


        :return: The offer_type of this EoscNodeEnvironmentOffer.
        :rtype: str
        """
        return self._offer_type

    @offer_type.setter
    def offer_type(self, offer_type: str):
        """Sets the offer_type of this EoscNodeEnvironmentOffer.


        :param offer_type: The offer_type of this EoscNodeEnvironmentOffer.
        :type offer_type: str
        """
        if offer_type is None:
            raise ValueError("Invalid value for `offer_type`, must not be `None`")  # noqa: E501

        self._offer_type = offer_type

    @property
    def cpus(self) -> int:
        """Gets the cpus of this EoscNodeEnvironmentOffer.


        :return: The cpus of this EoscNodeEnvironmentOffer.
        :rtype: int
        """
        return self._cpus

    @cpus.setter
    def cpus(self, cpus: int):
        """Sets the cpus of this EoscNodeEnvironmentOffer.


        :param cpus: The cpus of this EoscNodeEnvironmentOffer.
        :type cpus: int
        """

        self._cpus = cpus

    @property
    def gpus(self) -> int:
        """Gets the gpus of this EoscNodeEnvironmentOffer.


        :return: The gpus of this EoscNodeEnvironmentOffer.
        :rtype: int
        """
        return self._gpus

    @gpus.setter
    def gpus(self, gpus: int):
        """Sets the gpus of this EoscNodeEnvironmentOffer.


        :param gpus: The gpus of this EoscNodeEnvironmentOffer.
        :type gpus: int
        """

        self._gpus = gpus

    @property
    def memory(self) -> int:
        """Gets the memory of this EoscNodeEnvironmentOffer.

        RAM quota in GB  # noqa: E501

        :return: The memory of this EoscNodeEnvironmentOffer.
        :rtype: int
        """
        return self._memory

    @memory.setter
    def memory(self, memory: int):
        """Sets the memory of this EoscNodeEnvironmentOffer.

        RAM quota in GB  # noqa: E501

        :param memory: The memory of this EoscNodeEnvironmentOffer.
        :type memory: int
        """

        self._memory = memory

    @property
    def fast_storage(self) -> int:
        """Gets the fast_storage of this EoscNodeEnvironmentOffer.

        SSD or NVMe based (fast) storage quota in GB  # noqa: E501

        :return: The fast_storage of this EoscNodeEnvironmentOffer.
        :rtype: int
        """
        return self._fast_storage

    @fast_storage.setter
    def fast_storage(self, fast_storage: int):
        """Sets the fast_storage of this EoscNodeEnvironmentOffer.

        SSD or NVMe based (fast) storage quota in GB  # noqa: E501

        :param fast_storage: The fast_storage of this EoscNodeEnvironmentOffer.
        :type fast_storage: int
        """

        self._fast_storage = fast_storage

    @property
    def bulk_storage(self) -> int:
        """Gets the bulk_storage of this EoscNodeEnvironmentOffer.

        HDD based (slow) storage quota in GB  # noqa: E501

        :return: The bulk_storage of this EoscNodeEnvironmentOffer.
        :rtype: int
        """
        return self._bulk_storage

    @bulk_storage.setter
    def bulk_storage(self, bulk_storage: int):
        """Sets the bulk_storage of this EoscNodeEnvironmentOffer.

        HDD based (slow) storage quota in GB  # noqa: E501

        :param bulk_storage: The bulk_storage of this EoscNodeEnvironmentOffer.
        :type bulk_storage: int
        """

        self._bulk_storage = bulk_storage

    @property
    def s3_storage(self) -> int:
        """Gets the s3_storage of this EoscNodeEnvironmentOffer.

        S3 storage quota in GB  # noqa: E501

        :return: The s3_storage of this EoscNodeEnvironmentOffer.
        :rtype: int
        """
        return self._s3_storage

    @s3_storage.setter
    def s3_storage(self, s3_storage: int):
        """Sets the s3_storage of this EoscNodeEnvironmentOffer.

        S3 storage quota in GB  # noqa: E501

        :param s3_storage: The s3_storage of this EoscNodeEnvironmentOffer.
        :type s3_storage: int
        """

        self._s3_storage = s3_storage

    @property
    def registry_storage(self) -> int:
        """Gets the registry_storage of this EoscNodeEnvironmentOffer.

        Container Registry storage quota in GB  # noqa: E501

        :return: The registry_storage of this EoscNodeEnvironmentOffer.
        :rtype: int
        """
        return self._registry_storage

    @registry_storage.setter
    def registry_storage(self, registry_storage: int):
        """Sets the registry_storage of this EoscNodeEnvironmentOffer.

        Container Registry storage quota in GB  # noqa: E501

        :param registry_storage: The registry_storage of this EoscNodeEnvironmentOffer.
        :type registry_storage: int
        """

        self._registry_storage = registry_storage

    @property
    def credits_per_day(self) -> int:
        """Gets the credits_per_day of this EoscNodeEnvironmentOffer.


        :return: The credits_per_day of this EoscNodeEnvironmentOffer.
        :rtype: int
        """
        return self._credits_per_day

    @credits_per_day.setter
    def credits_per_day(self, credits_per_day: int):
        """Sets the credits_per_day of this EoscNodeEnvironmentOffer.


        :param credits_per_day: The credits_per_day of this EoscNodeEnvironmentOffer.
        :type credits_per_day: int
        """

        self._credits_per_day = credits_per_day
