from awm.models.allocation import Allocation
from awm.models.eosc_node_environment_offer import EoscNodeEnvironmentOffer  # noqa: F401,E501
from awm import util


class EoscNodeEnvironment(Allocation):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, kind: str = None, offer: EoscNodeEnvironmentOffer = None, project_id: str = None,
                 hostname: str = None, provisioned_on: str = None, expires_on: str = None,
                 node_name: str = None, node_ui: str = None, awm_api: str = None):  # noqa: E501
        """EoscNodeEnvironment - a model defined in Swagger

        :param kind: The kind of this EoscNodeEnvironment.  # noqa: E501
        :type kind: str
        :param offer: The offer of this EoscNodeEnvironment.  # noqa: E501
        :type offer: EoscNodeEnvironmentOffer
        :param project_id: The project_id of this EoscNodeEnvironment.  # noqa: E501
        :type project_id: str
        :param hostname: The hostname of this EoscNodeEnvironment.  # noqa: E501
        :type hostname: str
        :param provisioned_on: The provisioned_on of this EoscNodeEnvironment.  # noqa: E501
        :type provisioned_on: str
        :param expires_on: The expires_on of this EoscNodeEnvironment.  # noqa: E501
        :type expires_on: str
        :param node_name: The node_name of this EoscNodeEnvironment.  # noqa: E501
        :type node_name: str
        :param node_ui: The node_ui of this EoscNodeEnvironment.  # noqa: E501
        :type node_ui: str
        :param awm_api: The awm_api of this EoscNodeEnvironment.  # noqa: E501
        :type awm_api: str
        """
        self.swagger_types = {
            'kind': str,
            'offer': EoscNodeEnvironmentOffer,
            'project_id': str,
            'hostname': str,
            'provisioned_on': str,
            'expires_on': str,
            'node_name': str,
            'node_ui': str,
            'awm_api': str
        }

        self.attribute_map = {
            'kind': 'kind',
            'offer': 'offer',
            'project_id': 'projectId',
            'hostname': 'hostname',
            'provisioned_on': 'provisionedOn',
            'expires_on': 'expiresOn',
            'node_name': 'nodeName',
            'node_ui': 'nodeUI',
            'awm_api': 'awmAPI'
        }
        self._kind = kind
        self._offer = offer
        self._project_id = project_id
        self._hostname = hostname
        self._provisioned_on = provisioned_on
        self._expires_on = expires_on
        self._node_name = node_name
        self._node_ui = node_ui
        self._awm_api = awm_api

    @classmethod
    def from_dict(cls, dikt) -> 'EoscNodeEnvironment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EoscNodeEnvironment of this EoscNodeEnvironment.  # noqa: E501
        :rtype: EoscNodeEnvironment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def kind(self) -> str:
        """Gets the kind of this EoscNodeEnvironment.


        :return: The kind of this EoscNodeEnvironment.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind: str):
        """Sets the kind of this EoscNodeEnvironment.


        :param kind: The kind of this EoscNodeEnvironment.
        :type kind: str
        """

        self._kind = kind

    @property
    def offer(self) -> EoscNodeEnvironmentOffer:
        """Gets the offer of this EoscNodeEnvironment.


        :return: The offer of this EoscNodeEnvironment.
        :rtype: EoscNodeEnvironmentOffer
        """
        return self._offer

    @offer.setter
    def offer(self, offer: EoscNodeEnvironmentOffer):
        """Sets the offer of this EoscNodeEnvironment.


        :param offer: The offer of this EoscNodeEnvironment.
        :type offer: EoscNodeEnvironmentOffer
        """
        if offer is None:
            raise ValueError("Invalid value for `offer`, must not be `None`")  # noqa: E501

        self._offer = offer

    @property
    def project_id(self) -> str:
        """Gets the project_id of this EoscNodeEnvironment.


        :return: The project_id of this EoscNodeEnvironment.
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id: str):
        """Sets the project_id of this EoscNodeEnvironment.


        :param project_id: The project_id of this EoscNodeEnvironment.
        :type project_id: str
        """

        self._project_id = project_id

    @property
    def hostname(self) -> str:
        """Gets the hostname of this EoscNodeEnvironment.


        :return: The hostname of this EoscNodeEnvironment.
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname: str):
        """Sets the hostname of this EoscNodeEnvironment.


        :param hostname: The hostname of this EoscNodeEnvironment.
        :type hostname: str
        """

        self._hostname = hostname

    @property
    def provisioned_on(self) -> str:
        """Gets the provisioned_on of this EoscNodeEnvironment.


        :return: The provisioned_on of this EoscNodeEnvironment.
        :rtype: str
        """
        return self._provisioned_on

    @provisioned_on.setter
    def provisioned_on(self, provisioned_on: str):
        """Sets the provisioned_on of this EoscNodeEnvironment.


        :param provisioned_on: The provisioned_on of this EoscNodeEnvironment.
        :type provisioned_on: str
        """

        self._provisioned_on = provisioned_on

    @property
    def expires_on(self) -> str:
        """Gets the expires_on of this EoscNodeEnvironment.


        :return: The expires_on of this EoscNodeEnvironment.
        :rtype: str
        """
        return self._expires_on

    @expires_on.setter
    def expires_on(self, expires_on: str):
        """Sets the expires_on of this EoscNodeEnvironment.


        :param expires_on: The expires_on of this EoscNodeEnvironment.
        :type expires_on: str
        """

        self._expires_on = expires_on

    @property
    def node_name(self) -> str:
        """Gets the node_name of this EoscNodeEnvironment.

        Name of the EOSC node where this environment was allocated  # noqa: E501

        :return: The node_name of this EoscNodeEnvironment.
        :rtype: str
        """
        return self._node_name

    @node_name.setter
    def node_name(self, node_name: str):
        """Sets the node_name of this EoscNodeEnvironment.

        Name of the EOSC node where this environment was allocated  # noqa: E501

        :param node_name: The node_name of this EoscNodeEnvironment.
        :type node_name: str
        """
        if node_name is None:
            raise ValueError("Invalid value for `node_name`, must not be `None`")  # noqa: E501

        self._node_name = node_name

    @property
    def node_ui(self) -> str:
        """Gets the node_ui of this EoscNodeEnvironment.

        URL to the interactive UI of the EOSC node where this environment was allocated  # noqa: E501

        :return: The node_ui of this EoscNodeEnvironment.
        :rtype: str
        """
        return self._node_ui

    @node_ui.setter
    def node_ui(self, node_ui: str):
        """Sets the node_ui of this EoscNodeEnvironment.

        URL to the interactive UI of the EOSC node where this environment was allocated  # noqa: E501

        :param node_ui: The node_ui of this EoscNodeEnvironment.
        :type node_ui: str
        """

        self._node_ui = node_ui

    @property
    def awm_api(self) -> str:
        """Gets the awm_api of this EoscNodeEnvironment.

        Base URL for the AWM API of the EOSC node where this environment was allocated,  or null for environments private to the calling user that accessed via  explicit credentials  # noqa: E501

        :return: The awm_api of this EoscNodeEnvironment.
        :rtype: str
        """
        return self._awm_api

    @awm_api.setter
    def awm_api(self, awm_api: str):
        """Sets the awm_api of this EoscNodeEnvironment.

        Base URL for the AWM API of the EOSC node where this environment was allocated,  or null for environments private to the calling user that accessed via  explicit credentials  # noqa: E501

        :param awm_api: The awm_api of this EoscNodeEnvironment.
        :type awm_api: str
        """

        self._awm_api = awm_api
