from awm.models.base_model_ import Model
from awm import util


class Error(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _id: str = None, description: str = None, details: str = None):  # noqa: E501
        """Error - a model defined in Swagger

        :param id: The id of this Error.  # noqa: E501
        :type id: str
        :param description: The description of this Error.  # noqa: E501
        :type description: str
        :param details: The details of this Error.  # noqa: E501
        :type details: str
        """
        self.swagger_types = {
            'id': str,
            'description': str,
            'details': str
        }

        self.attribute_map = {
            'id': 'id',
            'description': 'description',
            'details': 'details'
        }
        self._id = _id
        self._description = description
        self._details = details

    @classmethod
    def from_dict(cls, dikt) -> 'Error':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Error of this Error.  # noqa: E501
        :rtype: Error
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Error.

        Error type  # noqa: E501

        :return: The id of this Error.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, _id: str):
        """Sets the id of this Error.

        Error type  # noqa: E501

        :param id: The id of this Error.
        :type id: str
        """

        self._id = _id

    @property
    def description(self) -> str:
        """Gets the description of this Error.

        Error message  # noqa: E501

        :return: The description of this Error.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Error.

        Error message  # noqa: E501

        :param description: The description of this Error.
        :type description: str
        """

        self._description = description

    @property
    def details(self) -> str:
        """Gets the details of this Error.

        Additional details about the error  # noqa: E501

        :return: The details of this Error.
        :rtype: str
        """
        return self._details

    @details.setter
    def details(self, details: str):
        """Sets the details of this Error.

        Additional details about the error  # noqa: E501

        :param details: The details of this Error.
        :type details: str
        """

        self._details = details
