from typing import List
from awm.models.base_model_ import Model
from awm import util


class ToolInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, kind: str = 'ToolInfo', _id: str = None, _type: str = None, blueprint: str = None,
                 blueprint_type: str = None, name: str = None, description: str = None,
                 author_name: str = None, author_email: str = None, organisation: str = None,
                 keywords: List[str] = None, _license: str = None, version: str = None, version_from: str = None,
                 repository: str = None, helpdesk: str = None, validated: bool = None,
                 validated_on: str = None, _self: str = None):
        """ToolInfo - a model defined in Swagger

        :param kind: The kind of this ToolInfo.
        :type kind: str
        :param id: The id of this ToolInfo.
        :type id: str
        :param type: The type of this ToolInfo.
        :type type: str
        :param blueprint: The blueprint of this ToolInfo.
        :type blueprint: str
        :param blueprint_type: The blueprint_type of this ToolInfo.
        :type blueprint_type: str
        :param name: The name of this ToolInfo.
        :type name: str
        :param description: The description of this ToolInfo.
        :type description: str
        :param author_name: The author_name of this ToolInfo.
        :type author_name: str
        :param author_email: The author_email of this ToolInfo.
        :type author_email: str
        :param organisation: The organisation of this ToolInfo.
        :type organisation: str
        :param keywords: The keywords of this ToolInfo.
        :type keywords: List[str]
        :param license: The license of this ToolInfo.
        :type license: str
        :param version: The version of this ToolInfo.
        :type version: str
        :param version_from: The version_from of this ToolInfo.
        :type version_from: str
        :param repository: The repository of this ToolInfo.
        :type repository: str
        :param helpdesk: The helpdesk of this ToolInfo.
        :type helpdesk: str
        :param validated: The validated of this ToolInfo.
        :type validated: bool
        :param validated_on: The validated_on of this ToolInfo.
        :type validated_on: str
        :param _self: The _self of this ToolInfo.
        :type _self: str
        """
        self.swagger_types = {
            'kind': str,
            'id': str,
            'type': str,
            'blueprint': str,
            'blueprint_type': str,
            'name': str,
            'description': str,
            'author_name': str,
            'author_email': str,
            'organisation': str,
            'keywords': List[str],
            'license': str,
            'version': str,
            'version_from': str,
            'repository': str,
            'helpdesk': str,
            'validated': bool,
            'validated_on': str,
            '_self': str
        }

        self.attribute_map = {
            'kind': 'kind',
            'id': 'id',
            'type': 'type',
            'blueprint': 'blueprint',
            'blueprint_type': 'blueprintType',
            'name': 'name',
            'description': 'description',
            'author_name': 'authorName',
            'author_email': 'authorEmail',
            'organisation': 'organisation',
            'keywords': 'keywords',
            'license': 'license',
            'version': 'version',
            'version_from': 'versionFrom',
            'repository': 'repository',
            'helpdesk': 'helpdesk',
            'validated': 'validated',
            'validated_on': 'validatedOn',
            '_self': 'self'
        }
        self._kind = kind
        self._id = _id
        self._type = _type
        self._blueprint = blueprint
        self._blueprint_type = blueprint_type
        self._name = name
        self._description = description
        self._author_name = author_name
        self._author_email = author_email
        self._organisation = organisation
        self._keywords = keywords
        self._license = _license
        self._version = version
        self._version_from = version_from
        self._repository = repository
        self._helpdesk = helpdesk
        self._validated = validated
        self._validated_on = validated_on
        self.__self = _self

    @classmethod
    def from_dict(cls, dikt) -> 'ToolInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ToolInfo of this ToolInfo.
        :rtype: ToolInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def kind(self) -> str:
        """Gets the kind of this ToolInfo.


        :return: The kind of this ToolInfo.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind: str):
        """Sets the kind of this ToolInfo.


        :param kind: The kind of this ToolInfo.
        :type kind: str
        """

        self._kind = kind

    @property
    def id(self) -> str:
        """Gets the id of this ToolInfo.

        Unique identifier for this tool blueprint

        :return: The id of this ToolInfo.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, _id: str):
        """Sets the id of this ToolInfo.

        Unique identifier for this tool blueprint

        :param id: The id of this ToolInfo.
        :type id: str
        """

        self._id = _id

    @property
    def type(self) -> str:
        """Gets the type of this ToolInfo.


        :return: The type of this ToolInfo.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, _type: str):
        """Sets the type of this ToolInfo.


        :param type: The type of this ToolInfo.
        :type type: str
        """
        if _type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = _type

    @property
    def blueprint(self) -> str:
        """Gets the blueprint of this ToolInfo.

        Blueprint of the tool's workload

        :return: The blueprint of this ToolInfo.
        :rtype: str
        """
        return self._blueprint

    @blueprint.setter
    def blueprint(self, blueprint: str):
        """Sets the blueprint of this ToolInfo.

        Blueprint of the tool's workload

        :param blueprint: The blueprint of this ToolInfo.
        :type blueprint: str
        """
        if blueprint is None:
            raise ValueError("Invalid value for `blueprint`, must not be `None`")

        self._blueprint = blueprint

    @property
    def blueprint_type(self) -> str:
        """Gets the blueprint_type of this ToolInfo.


        :return: The blueprint_type of this ToolInfo.
        :rtype: str
        """
        return self._blueprint_type

    @blueprint_type.setter
    def blueprint_type(self, blueprint_type: str):
        """Sets the blueprint_type of this ToolInfo.


        :param blueprint_type: The blueprint_type of this ToolInfo.
        :type blueprint_type: str
        """
        if blueprint_type is None:
            raise ValueError("Invalid value for `blueprint_type`, must not be `None`")

        self._blueprint_type = blueprint_type

    @property
    def name(self) -> str:
        """Gets the name of this ToolInfo.


        :return: The name of this ToolInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ToolInfo.


        :param name: The name of this ToolInfo.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this ToolInfo.


        :return: The description of this ToolInfo.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ToolInfo.


        :param description: The description of this ToolInfo.
        :type description: str
        """

        self._description = description

    @property
    def author_name(self) -> str:
        """Gets the author_name of this ToolInfo.


        :return: The author_name of this ToolInfo.
        :rtype: str
        """
        return self._author_name

    @author_name.setter
    def author_name(self, author_name: str):
        """Sets the author_name of this ToolInfo.


        :param author_name: The author_name of this ToolInfo.
        :type author_name: str
        """

        self._author_name = author_name

    @property
    def author_email(self) -> str:
        """Gets the author_email of this ToolInfo.


        :return: The author_email of this ToolInfo.
        :rtype: str
        """
        return self._author_email

    @author_email.setter
    def author_email(self, author_email: str):
        """Sets the author_email of this ToolInfo.


        :param author_email: The author_email of this ToolInfo.
        :type author_email: str
        """

        self._author_email = author_email

    @property
    def organisation(self) -> str:
        """Gets the organisation of this ToolInfo.


        :return: The organisation of this ToolInfo.
        :rtype: str
        """
        return self._organisation

    @organisation.setter
    def organisation(self, organisation: str):
        """Sets the organisation of this ToolInfo.


        :param organisation: The organisation of this ToolInfo.
        :type organisation: str
        """

        self._organisation = organisation

    @property
    def keywords(self) -> List[str]:
        """Gets the keywords of this ToolInfo.


        :return: The keywords of this ToolInfo.
        :rtype: List[str]
        """
        return self._keywords

    @keywords.setter
    def keywords(self, keywords: List[str]):
        """Sets the keywords of this ToolInfo.


        :param keywords: The keywords of this ToolInfo.
        :type keywords: List[str]
        """

        self._keywords = keywords

    @property
    def license(self) -> str:
        """Gets the license of this ToolInfo.


        :return: The license of this ToolInfo.
        :rtype: str
        """
        return self._license

    @license.setter
    def license(self, _license: str):
        """Sets the license of this ToolInfo.


        :param license: The license of this ToolInfo.
        :type license: str
        """

        self._license = _license

    @property
    def version(self) -> str:
        """Gets the version of this ToolInfo.


        :return: The version of this ToolInfo.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this ToolInfo.


        :param version: The version of this ToolInfo.
        :type version: str
        """

        self._version = version

    @property
    def version_from(self) -> str:
        """Gets the version_from of this ToolInfo.


        :return: The version_from of this ToolInfo.
        :rtype: str
        """
        return self._version_from

    @version_from.setter
    def version_from(self, version_from: str):
        """Sets the version_from of this ToolInfo.


        :param version_from: The version_from of this ToolInfo.
        :type version_from: str
        """

        self._version_from = version_from

    @property
    def repository(self) -> str:
        """Gets the repository of this ToolInfo.


        :return: The repository of this ToolInfo.
        :rtype: str
        """
        return self._repository

    @repository.setter
    def repository(self, repository: str):
        """Sets the repository of this ToolInfo.


        :param repository: The repository of this ToolInfo.
        :type repository: str
        """

        self._repository = repository

    @property
    def helpdesk(self) -> str:
        """Gets the helpdesk of this ToolInfo.


        :return: The helpdesk of this ToolInfo.
        :rtype: str
        """
        return self._helpdesk

    @helpdesk.setter
    def helpdesk(self, helpdesk: str):
        """Sets the helpdesk of this ToolInfo.


        :param helpdesk: The helpdesk of this ToolInfo.
        :type helpdesk: str
        """

        self._helpdesk = helpdesk

    @property
    def validated(self) -> bool:
        """Gets the validated of this ToolInfo.


        :return: The validated of this ToolInfo.
        :rtype: bool
        """
        return self._validated

    @validated.setter
    def validated(self, validated: bool):
        """Sets the validated of this ToolInfo.


        :param validated: The validated of this ToolInfo.
        :type validated: bool
        """

        self._validated = validated

    @property
    def validated_on(self) -> str:
        """Gets the validated_on of this ToolInfo.


        :return: The validated_on of this ToolInfo.
        :rtype: str
        """
        return self._validated_on

    @validated_on.setter
    def validated_on(self, validated_on: str):
        """Sets the validated_on of this ToolInfo.


        :param validated_on: The validated_on of this ToolInfo.
        :type validated_on: str
        """

        self._validated_on = validated_on

    @property
    def _self(self) -> str:
        """Gets the _self of this ToolInfo.

        Endpoint that returns the details of this tool blueprint

        :return: The _self of this ToolInfo.
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self: str):
        """Sets the _self of this ToolInfo.

        Endpoint that returns the details of this tool blueprint

        :param _self: The _self of this ToolInfo.
        :type _self: str
        """

        self.__self = _self
